# Aggregate Functions RLAB

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35],
    'Fee' :[20000,25000,26000,22000,24000,35000],
    'Duration':['30day','40days','35days','40days','60days','60days'],
    'Discount':[1000,2300,1200,2500,2000,2000]
}

df = pd.DataFrame(data)

In [3]:
df.head()

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000

In [6]:
total_sum = df['Value'].aggregate('sum')
total_sum

np.int64(135)

In [8]:
total_sum2 = df['Value'].sum()
total_sum2

np.int64(135)

In [10]:
# cumulative sum/running total
df[['Value']].cumsum()

   Value
0     10
1     25
2     45
3     70
4    100
5    135

In [12]:
total_mean = df['Value'].aggregate('mean')
total_mean

np.float64(22.5)

In [13]:
total_mean2 = df['Value'].mean()

total_mean2

np.float64(22.5)

In [20]:
total_max= df['Value'].aggregate('max')
total_max

np.int64(35)

In [24]:
total_max2 = df['Value'].max()
total_max2

np.int64(35)

In [19]:
total_min= df['Value'].aggregate('min')
total_min

np.int64(10)

In [25]:
total_min2 = df['Value'].min()
total_min2

np.int64(10)

In [22]:
total_std = df['Value'].aggregate('std')
total_count = df['Value'].aggregate('count')

print(total_count)
print(total_std)

6
9.354143466934854

In [26]:
total_std2 = df['Value'].std()
total_count2 = df['Value'].count()

print(total_count2)
print(total_std2)

6
9.354143466934854

#### Applying multiple aggregates

In [27]:
result = df[['Fee', 'Discount']].agg('sum')
result

Fee         152000
Discount     11000
dtype: int64

In [29]:
# Determine the total of eachg group with and agg function
result_group = df.groupby('Category')[['Fee', 'Discount']].agg('sum')

print(result_group)

            Fee  Discount
Category
A         69000      5300
B         83000      5700